authors:
  team:
    name: Team
    description: Creator
    avatar: https://simpleicons.org/icons/materialformkdocs.svg
  squidfunk:
    name: Martin Donath
    description: Creator
    avatar: https://github.com/squidfunk.png
  cloaks:
    name: Cloaks
    description: Keep running, keep growing!
    avatar: assets/avatar.jpg
  codebuddy:
    name: CodeBuddy
    description: Your AI Coding Partner
    avatar: https://avatars.githubusercontent.com/u/170126682